#!/usr/bin/env node
// Builds the agent pack: the Claude Code plugin and marketplace at the
// repository root, the skills under skills/, and the skills discovery index
// under web/public/.well-known/agent-skills/.
//
//   node scripts/build-pack.mjs           write every generated file
//   node scripts/build-pack.mjs --check   write nothing; exit 1 when a file on disk differs from what would be written
//   --root <dir>                          check or write another copy of the repository (the tests use it)
//
// Open core. The three core skills carry the method and the output format of a
// core profile, copied from the engine in web/public at build time and never
// retyped. Every other profile is hosted: its method is not in the engine and
// never reaches the pack. The build refuses to write anything when
//   - a profile marked hosted carries method text in web/public/profiles.mjs,
//   - the engine's core profiles are not exactly general, solidity and report,
//   - a skill names a profile that is not core, or
//   - web/private exists and any generated file shares an eight-word run with
//     the hosted method (the leak audit's shingle check). Only file names and
//     counts are printed, never the matched words.
//
// The plugin version is the product version in web/package.json.

import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PACK_DIR = join(ROOT, 'pack');
/** Folders the build owns: a file in them that it does not write is stray. */
const GENERATED_FOLDERS = ['skills', 'web/public/.well-known/agent-skills'];
const PRIVATE_MODULE = join(ROOT, 'web', 'private', 'operator-profiles.mjs');

export const DISCOVERY_SCHEMA = 'https://schemas.agentskills.io/discovery/0.2.0/schema.json';
const FENCE = '~~~~';
const GENERATED_NOTE = '<!-- GENERATED by scripts/build-pack.mjs from pack/ and the engine in web/public. Edit those, then run the script. -->';

const posix = (path) => path.split(sep).join('/');
const sha256 = (text) => createHash('sha256').update(text, 'utf8').digest('hex');
const json = (value) => `${JSON.stringify(value, null, 2)}\n`;
/** A YAML scalar. JSON string syntax is valid YAML double-quoted syntax. */
const yamlString = (text) => JSON.stringify(text);

async function engine() {
  const load = (path) => import(pathToFileURL(join(ROOT, path)).href);
  const [profiles, core, evidence, pack, pkg] = await Promise.all([
    load('web/public/profiles.mjs'),
    load('web/public/review-core.mjs'),
    load('web/public/evidence.mjs'),
    load('pack/skills.mjs'),
    readFile(join(ROOT, 'web', 'package.json'), 'utf8').then(JSON.parse),
  ]);
  return { ...profiles, ...core, ...evidence, pack, version: pkg.version };
}

/**
 * Throws unless the engine holds exactly the open core: three core profiles
 * with method text, and every hosted profile with none.
 */
export function assertOpenCore({ PROFILES, pack }) {
  const problems = [];
  for (const profile of PROFILES) {
    if (profile.hosted && (profile.instructions || profile.extraFormat)) {
      problems.push(`${profile.id} is hosted and carries method text in web/public/profiles.mjs`);
    }
  }
  const core = PROFILES.filter((profile) => !profile.hosted).map((profile) => profile.id).sort();
  if (core.join() !== [...pack.CORE_PROFILES].sort().join()) {
    problems.push(`the core profiles are ${core.join(', ')}; the pack is built for ${pack.CORE_PROFILES.join(', ')}`);
  }
  for (const skill of pack.SKILLS) {
    if (skill.kind !== 'core') continue;
    const profile = PROFILES.find((entry) => entry.id === skill.profile);
    if (!profile || profile.hosted || !pack.CORE_PROFILES.includes(skill.profile) || !profile.instructions.trim()) {
      problems.push(`skill ${skill.name} names ${skill.profile}, which is not a core profile with method text`);
    }
  }
  if (problems.length) throw new Error(`Refusing to build the pack:\n${problems.map((line) => `  ${line}`).join('\n')}`);
}

/** The system prompt the engine sends for a core profile: the review contract, the method and the output format. */
async function enginePrompt(e, profileId) {
  const prepared = await e.prepareReview([{ name: 'input.txt', content: 'x' }], '', profileId);
  const system = prepared.messages[0].content;
  const profile = e.reviewProfile(profileId);
  if (!system.includes(profile.instructions) || !system.includes(e.outputFormat(profile)) || !system.includes(e.REVIEW_CONTRACT)) {
    throw new Error(`The engine prompt for ${profileId} does not hold its method and output format.`);
  }
  if (system.includes(FENCE)) throw new Error(`The engine prompt for ${profileId} contains ${FENCE}; choose another fence.`);
  return system;
}

function frontmatter(skill, e, extra = []) {
  const lines = [
    '---',
    `name: ${skill.name}`,
    `description: ${yamlString(skill.description)}`,
    'license: MIT',
  ];
  if (skill.manualOnly) lines.push('disable-model-invocation: true');
  lines.push('metadata:', '  author: "Tradi3"', `  version: ${yamlString(e.version)}`, `  homepage: ${yamlString(e.pack.SITE)}`, ...extra, '---');
  return lines.join('\n');
}

function choiceText(field) {
  // The block prints the label of the chosen option, so the label is what the agent writes.
  return field.options.map((option) => `"${option.label}"`).join('; ');
}

/** What the profile reads, from the engine: the files in order, the Context fields, the limits and the default request. */
function readsSection(e, profile) {
  const needs = e.profileNeeds(profile.id);
  const files = needs.inputs.map((input) => `- ${input.label}: ${input.hint}`);
  const fieldLine = (field) => {
    const values = field.kind === 'choice' ? ` Write one of: ${choiceText(field)}.` : '';
    return `- ${field.label} (\`${field.key}\`): ${field.hint}${values}`;
  };
  // The block the engine prints for an empty Context, in the profile's mode.
  const mode = profile.mode === 'either' ? 'bounty' : profile.mode;
  const base = e.evidenceNotes({}, mode);
  const printed = new Set(['target', 'scope', 'version', 'proof', 'prior', 'notes']);
  const extra = needs.context.filter((field) => !printed.has(field.key));
  const limits = `${e.LIMITS.files} files, ${e.LIMITS.fileBytes / 1000} KB each, ${e.LIMITS.totalBytes / 1000} KB and ${e.LIMITS.totalLines.toLocaleString('en-US')} lines together`;
  const lines = [
    '## What it reads',
    '',
    'Files, most decisive first:',
    '',
    ...files,
    '',
    `Context. Put this block above the files and replace each value the user has given.${profile.mode === 'either' ? ' Write `Mode: own-code` for code the user ships.' : ''}`,
    '',
    '```text',
    base,
    '```',
    '',
    'The fields it always carries:',
    '',
    ...e.CONTEXT_FIELDS.filter((field) => printed.has(field.key)).map(fieldLine),
  ];
  if (extra.length) {
    lines.push(
      '',
      'This profile also reads these. Add each one the user has given to the block as `Label: value`, with a multi-line value on the lines below its label:',
      '',
      ...extra.map(fieldLine),
    );
  }
  lines.push('', `Limits: up to ${limits}.`, '', `Request. When the user names no focus, the request is: "${profile.defaultFocus}"`);
  return lines.join('\n');
}

async function coreSkill(skill, e) {
  const profile = e.reviewProfile(skill.profile);
  const prompt = await enginePrompt(e, profile.id);
  const wrapper = (await readFile(join(PACK_DIR, skill.wrapper), 'utf8')).trim();
  const hosted = `Bounty Operator runs the same check hosted, with an evidence packet that verifies at ${e.VERIFY_URL}, and Operator adds the eight-stage gauntlet: ${e.pack.SITE}`;
  const body = [
    `# ${skill.title}`,
    wrapper,
    readsSection(e, profile),
    [
      '## Reviewer instructions',
      '',
      `The method and the output format of the ${profile.name} profile, exactly as the Bounty Operator engine sends them to a model. Follow them as written.`,
      '',
      `${FENCE}text`,
      prompt,
      FENCE,
    ].join('\n'),
    ['## Hosted run', '', hosted].join('\n'),
  ].join('\n\n');
  const meta = [`  profile: ${yamlString(profile.id)}`, `  profile-sha256: ${yamlString(sha256(prompt))}`];
  return `${frontmatter(skill, e, meta)}\n${GENERATED_NOTE}\n\n${body}\n`;
}

async function orchestratorSkill(skill, e) {
  const body = (await readFile(join(PACK_DIR, skill.body), 'utf8')).trim();
  return `${frontmatter(skill, e)}\n${GENERATED_NOTE}\n\n# ${skill.title}\n\n${body}\n`;
}

/** Codex reads agents/openai.yaml beside SKILL.md: a manual-only skill turns implicit invocation off there. */
function openaiYaml(skill) {
  return [
    'interface:',
    `  display_name: ${yamlString(skill.title)}`,
    `  short_description: ${yamlString(skill.shortDescription ?? skill.title)}`,
    'policy:',
    '  allow_implicit_invocation: false',
    '',
  ].join('\n');
}

function pluginManifest(e) {
  const { pack } = e;
  return {
    name: 'bounty-operator',
    displayName: 'Bounty Operator',
    version: e.version,
    description:
      'Find the hole in your report before the triager does. Skills that argue against a security finding or a draft report before it is filed, on your own model, and the Bounty Operator MCP server for the hosted eight-stage gauntlet.',
    author: { name: 'Tradi3', url: pack.SITE },
    homepage: pack.SITE,
    repository: pack.REPOSITORY,
    license: 'MIT',
    keywords: ['bug-bounty', 'security', 'smart-contracts', 'solidity', 'audit', 'code-review', 'triage', 'mcp'],
    mcpServers: {
      'bounty-operator': {
        type: 'http',
        url: pack.MCP_ENDPOINT,
        headers: {
          Authorization: `Bearer \${${pack.TOKEN_VAR}:-}`,
          'X-Provider-Key': `\${${pack.PROVIDER_KEY_VAR}:-}`,
        },
      },
    },
  };
}

function marketplace(e) {
  return {
    name: 'bounty-operator',
    description: 'Bounty Operator: pre-submission review for bug bounty findings and draft reports.',
    owner: { name: 'Tradi3', url: e.pack.SITE },
    plugins: [
      {
        name: 'bounty-operator',
        source: './',
        description:
          'Challenge a draft report, review Solidity or any code for security bugs on your own model, and run the hosted gauntlet through the Bounty Operator MCP server.',
        category: 'security',
        tags: ['bug-bounty', 'security', 'solidity', 'audit'],
      },
    ],
  };
}

/** Every generated file, by repository-relative path, in a fixed order. */
export async function buildPack() {
  const e = await engine();
  assertOpenCore(e);
  if (e.GAUNTLET.length !== 8) throw new Error(`The gauntlet skill is written for eight stages; the engine has ${e.GAUNTLET.length}.`);
  const coreStages = e.GAUNTLET.filter((id) => !e.reviewProfile(id).hosted);
  if (coreStages.join() !== 'report') throw new Error(`The gauntlet skill runs the report stage as the one core stage; the engine has ${coreStages.join(', ') || 'none'}.`);

  const outputs = new Map();
  const index = [];
  for (const skill of e.pack.SKILLS) {
    const text = skill.kind === 'core' ? await coreSkill(skill, e) : await orchestratorSkill(skill, e);
    outputs.set(`skills/${skill.name}/SKILL.md`, text);
    if (skill.manualOnly) outputs.set(`skills/${skill.name}/agents/openai.yaml`, openaiYaml(skill));
    outputs.set(`web/public/.well-known/agent-skills/${skill.name}/SKILL.md`, text);
    index.push({
      name: skill.name,
      type: 'skill-md',
      description: skill.description,
      url: `/.well-known/agent-skills/${skill.name}/SKILL.md`,
      digest: `sha256:${sha256(text)}`,
    });
  }
  outputs.set('web/public/.well-known/agent-skills/index.json', json({ $schema: DISCOVERY_SCHEMA, skills: index }));
  outputs.set('.claude-plugin/plugin.json', json(pluginManifest(e)));
  outputs.set('.claude-plugin/marketplace.json', json(marketplace(e)));

  await assertNoHostedText(outputs);
  return { outputs, version: e.version };
}

/** With the private module present, refuses any output that shares an eight-word run with the hosted method. */
async function assertNoHostedText(outputs) {
  if (!existsSync(PRIVATE_MODULE)) return;
  const { privateShingles, hitsIn } = await import(pathToFileURL(join(ROOT, 'scripts', 'leak-audit.mjs')).href);
  const shingles = await privateShingles();
  const found = [];
  for (const [path, text] of outputs) {
    const hits = hitsIn(text, shingles);
    if (hits.length) found.push(`${path}: ${hits.length} run${hits.length === 1 ? '' : 's'} of hosted method text`);
  }
  if (found.length) throw new Error(`Refusing to build the pack:\n${found.map((line) => `  ${line}`).join('\n')}`);
}

async function filesUnder(directory, base) {
  const found = [];
  for (const entry of await readdir(directory, { withFileTypes: true }).catch(() => [])) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await filesUnder(path, base)));
    else found.push(posix(relative(base, path)));
  }
  return found;
}

/** Files in the generated folders under `target` that the build no longer writes. */
async function strayFiles(outputs, target) {
  const present = [];
  for (const folder of GENERATED_FOLDERS) present.push(...(await filesUnder(join(target, folder), target)));
  return present.filter((path) => !outputs.has(path));
}

const readText = (target, path) => readFile(join(target, path), 'utf8').catch(() => null);

/**
 * Lists what differs between the generated files and the files under `target`
 * (the repository root by default).
 *
 * @param {{ target?: string }} [options]
 */
export async function checkPack({ target = ROOT } = {}) {
  const { outputs } = await buildPack();
  const problems = [];
  for (const [path, text] of outputs) {
    const current = await readText(target, path);
    if (current === null) problems.push(`${path} is missing`);
    else if (current.replace(/\r\n/g, '\n') !== text) problems.push(`${path} is out of date`);
  }
  for (const path of await strayFiles(outputs, target)) problems.push(`${path} is not generated by the pack`);
  return problems;
}

/**
 * Writes every generated file under `target` (the repository root by default)
 * and removes files in the generated folders that the build no longer writes.
 *
 * @param {{ target?: string }} [options]
 */
export async function writePack({ target = ROOT } = {}) {
  const { outputs, version } = await buildPack();
  const written = [];
  for (const [path, text] of outputs) {
    if ((await readText(target, path)) === text) continue;
    await mkdir(dirname(join(target, path)), { recursive: true });
    await writeFile(join(target, path), text);
    written.push(path);
  }
  const removed = await strayFiles(outputs, target);
  for (const path of removed) await rm(join(target, path));
  return { written, removed, total: outputs.size, version };
}

/** `--root <dir>` points the check or the write at another copy of the repository. */
function targetFrom(argv) {
  const at = argv.indexOf('--root');
  if (at === -1) return ROOT;
  const value = argv[at + 1];
  if (!value || value.startsWith('--')) throw new Error('--root needs a directory.');
  return resolve(value);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    if (process.argv.includes('--check')) {
      const problems = await checkPack({ target: targetFrom(process.argv) });
      if (problems.length) {
        console.error(`Agent pack: ${problems.length} problem${problems.length === 1 ? '' : 's'}. Run node scripts/build-pack.mjs and commit the result.`);
        for (const problem of problems) console.error(`  ${problem}`);
        process.exitCode = 1;
      } else {
        console.log('Agent pack: every generated file matches its source.');
      }
    } else {
      const { written, removed, total, version } = await writePack({ target: targetFrom(process.argv) });
      console.log(`Agent pack ${version}: ${total} files, ${written.length} written, ${removed.length} removed.`);
      for (const path of written) console.log(`  wrote ${path}`);
      for (const path of removed) console.log(`  removed ${path}`);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
