// Tests for the agent pack and its generator, scripts/build-pack.mjs.
//
//   node --test pack/tests/*.test.mjs
//
// They read the engine in web/public and the pack sources in pack/, and write
// only to a temporary folder. With web/private present they also run the leak
// audit's shingle check over every generated file; a failure names the file
// and the number of matching runs, never the words.

import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { promisify } from 'node:util';

import { assertOpenCore, buildPack, checkPack, writePack } from '../../scripts/build-pack.mjs';
import { CORE_PROFILES, PROVIDER_KEY_VAR, SKILLS, TOKEN_VAR } from '../skills.mjs';
import { GAUNTLET, PROFILES } from '../../web/public/profiles.mjs';
import { prepareReview } from '../../web/public/review-core.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SCRIPT = join(ROOT, 'scripts', 'build-pack.mjs');
const PRIVATE_MODULE = join(ROOT, 'web', 'private', 'operator-profiles.mjs');
const run = promisify(execFile);

// Agent Skills specification (https://agentskills.io/specification) and the
// Claude Code skills reference (https://code.claude.com/docs/en/skills).
const SPEC_FIELDS = new Set(['name', 'description', 'license', 'compatibility', 'metadata', 'allowed-tools']);
const NAME = /^(?!-)(?!.*--)[a-z0-9-]{1,64}(?<!-)$/;
const DESCRIPTION_MAX = 1024;
const CLAUDE_LISTING_MAX = 1536;
const SKILL_MD_MAX_LINES = 500;

const tempDir = () => mkdtemp(join(tmpdir(), 'bo-pack-'));
const read = (path) => readFile(join(ROOT, path), 'utf8');

/**
 * Parses the frontmatter subset the pack writes: `key: value` lines, values
 * plain or JSON-quoted, and one `metadata:` map of two-space-indented
 * `key: "value"` lines. Anything else fails, so a malformed file cannot pass.
 */
function frontmatter(text) {
  const lines = text.split('\n');
  assert.equal(lines[0], '---', 'the opening --- is the first line');
  const end = lines.indexOf('---', 1);
  assert.ok(end > 0, 'the frontmatter is closed');
  const fields = {};
  let map = null;
  const scalar = (raw) => (raw.startsWith('"') ? JSON.parse(raw) : raw);
  for (const line of lines.slice(1, end)) {
    const nested = /^ {2}([a-z0-9-]+): (.+)$/.exec(line);
    if (nested && map) {
      map[nested[1]] = scalar(nested[2]);
      continue;
    }
    const top = /^([a-z][a-z0-9_-]*):(?: (.+))?$/.exec(line);
    assert.ok(top, `frontmatter line parses: ${line}`);
    if (top[2] === undefined) {
      map = {};
      fields[top[1]] = map;
    } else {
      map = null;
      fields[top[1]] = scalar(top[2]);
    }
  }
  return { fields, body: lines.slice(end + 1).join('\n') };
}

test('generation is deterministic', async () => {
  const first = await buildPack();
  const second = await buildPack();
  assert.deepEqual([...first.outputs.keys()], [...second.outputs.keys()]);
  for (const [path, text] of first.outputs) assert.equal(second.outputs.get(path), text, path);
});

test('the files on disk match the generator', async () => {
  assert.deepEqual(await checkPack(), []);
});

test('--check catches a stale skill, a missing file and a stray file', async () => {
  const target = await tempDir();
  try {
    await writePack({ target });
    assert.deepEqual(await checkPack({ target }), []);
    const clean = await run(process.execPath, [SCRIPT, '--check', '--root', target]);
    assert.match(clean.stdout, /matches its source/);

    const skill = join(target, 'skills', 'challenge-report', 'SKILL.md');
    await writeFile(skill, `${await readFile(skill, 'utf8')}\nA stale line.\n`);
    await rm(join(target, '.claude-plugin', 'plugin.json'));
    await writeFile(join(target, 'skills', 'challenge-report', 'notes.md'), 'not generated\n');

    const problems = await checkPack({ target });
    assert.ok(problems.includes('skills/challenge-report/SKILL.md is out of date'), problems.join('\n'));
    assert.ok(problems.includes('.claude-plugin/plugin.json is missing'), problems.join('\n'));
    assert.ok(problems.includes('skills/challenge-report/notes.md is not generated by the pack'), problems.join('\n'));

    await assert.rejects(run(process.execPath, [SCRIPT, '--check', '--root', target]), (error) => {
      assert.equal(error.code, 1);
      assert.match(error.stderr, /skills\/challenge-report\/SKILL\.md is out of date/);
      return true;
    });
  } finally {
    await rm(target, { recursive: true, force: true });
  }
});

test('every SKILL.md has valid frontmatter within the documented limits', async () => {
  const { outputs } = await buildPack();
  const names = new Set();
  for (const skill of SKILLS) {
    const text = outputs.get(`skills/${skill.name}/SKILL.md`);
    assert.ok(text, skill.name);
    assert.equal(await read(`skills/${skill.name}/SKILL.md`), text);
    const { fields, body } = frontmatter(text);

    assert.match(fields.name, NAME, 'name follows the naming rule');
    assert.equal(fields.name, skill.name, 'name matches the folder');
    assert.ok(!names.has(fields.name), 'names are unique');
    names.add(fields.name);
    assert.notEqual(fields.name, 'code-review', 'code-review would replace a bundled Claude Code command');

    assert.equal(typeof fields.description, 'string');
    assert.ok(fields.description.length > 0 && fields.description.length <= DESCRIPTION_MAX, `${skill.name}: description is ${fields.description.length} characters`);
    assert.ok(fields.description.length <= CLAUDE_LISTING_MAX);
    assert.doesNotMatch(fields.description, /[<>]/, 'no angle brackets in a description');
    assert.equal(fields.license, 'MIT');

    for (const key of Object.keys(fields)) {
      const allowed = SPEC_FIELDS.has(key) || (key === 'disable-model-invocation' && skill.manualOnly);
      assert.ok(allowed, `${skill.name}: ${key} is not a field this skill may carry`);
    }
    if (skill.manualOnly) assert.equal(fields['disable-model-invocation'], 'true');
    else assert.equal(fields['disable-model-invocation'], undefined);

    assert.equal(typeof fields.metadata, 'object');
    for (const [key, value] of Object.entries(fields.metadata)) assert.equal(typeof value, 'string', `metadata.${key} is a string`);

    assert.ok(text.split('\n').length <= SKILL_MD_MAX_LINES, `${skill.name} is under ${SKILL_MD_MAX_LINES} lines`);
    assert.match(body, new RegExp(`^# ${skill.title}$`, 'm'));
  }
  assert.deepEqual([...names].sort(), ['challenge-report', 'code-security-review', 'gauntlet', 'hunt-with-gate', 'solidity-review']);
});

test('the manual-only skill is manual in Codex too', async () => {
  const yaml = await read('skills/hunt-with-gate/agents/openai.yaml');
  assert.match(yaml, /^policy:\n {2}allow_implicit_invocation: false$/m);
});

test('the core skills carry exactly the engine text of the three core profiles', async () => {
  const { outputs } = await buildPack();
  const core = SKILLS.filter((skill) => skill.kind === 'core');
  assert.deepEqual(core.map((skill) => skill.profile).sort(), [...CORE_PROFILES].sort());
  for (const skill of core) {
    const prepared = await prepareReview([{ name: 'input.txt', content: 'x' }], '', skill.profile);
    const prompt = prepared.messages[0].content;
    const text = outputs.get(`skills/${skill.name}/SKILL.md`);
    assert.ok(text.includes(`~~~~text\n${prompt}\n~~~~`), `${skill.name} carries the ${skill.profile} prompt verbatim`);
    assert.match(text, /^## Hosted run$/m);
    assert.ok(text.includes('https://bountyoperator.com'));
  }
});

test('no hosted profile reaches the pack', async () => {
  const { outputs } = await buildPack();
  const hosted = PROFILES.filter((profile) => profile.hosted);
  assert.ok(hosted.length >= 10);
  for (const profile of hosted) {
    assert.equal(profile.instructions, '', `${profile.id} has no method in the public engine`);
    assert.equal(profile.extraFormat, '', `${profile.id} has no format in the public engine`);
  }
  // The orchestrators hold no reviewer instructions of any kind.
  for (const skill of SKILLS.filter((entry) => entry.kind === 'orchestrator')) {
    const text = outputs.get(`skills/${skill.name}/SKILL.md`);
    assert.doesNotMatch(text, /~~~~|## Reviewer instructions|You are a security reviewer/);
  }
  // Only the three core profiles carry a profile line in their metadata.
  const profiles = [...outputs.values()].flatMap((text) => [...text.matchAll(/^ {2}profile: "([^"]+)"$/gm)].map((match) => match[1]));
  assert.deepEqual([...new Set(profiles)].sort(), [...CORE_PROFILES].sort());
});

test('the generator refuses a hosted profile that carries method text', () => {
  const pack = { CORE_PROFILES, SKILLS };
  assert.doesNotThrow(() => assertOpenCore({ PROFILES, pack }));
  const leaked = PROFILES.map((profile) => (profile.id === 'triage' ? { ...profile, instructions: 'Some method.' } : profile));
  assert.throws(() => assertOpenCore({ PROFILES: leaked, pack }), /triage is hosted and carries method text/);
  const opened = PROFILES.map((profile) => (profile.id === 'scope' ? { ...profile, hosted: false, instructions: 'Some method.' } : profile));
  assert.throws(() => assertOpenCore({ PROFILES: opened, pack }), /the core profiles are/);
  const misnamed = { CORE_PROFILES, SKILLS: [...SKILLS, { name: 'scope-check', kind: 'core', profile: 'scope' }] };
  assert.throws(() => assertOpenCore({ PROFILES, pack: misnamed }), /scope-check names scope/);
});

test('no generated file shares an eight-word run with the hosted method', { skip: !existsSync(PRIVATE_MODULE) && 'web/private is not in this checkout' }, async () => {
  const { privateShingles, hitsIn } = await import(pathToFileURL(join(ROOT, 'scripts', 'leak-audit.mjs')).href);
  const shingles = await privateShingles();
  assert.ok(shingles.size > 0);
  const { outputs } = await buildPack();
  const sources = ['pack/skills.mjs', 'pack/gauntlet.md', 'pack/hunt-with-gate.md', ...SKILLS.filter((skill) => skill.wrapper).map((skill) => `pack/${skill.wrapper}`)];
  const texts = new Map([...outputs, ...(await Promise.all(sources.map(async (path) => [path, await read(path)])))]);
  const found = [];
  for (const [path, text] of texts) {
    const hits = hitsIn(text, shingles).length;
    if (hits) found.push(`${path}: ${hits}`);
  }
  // Only file names and counts: the matched words stay private.
  assert.deepEqual(found, []);
});

test('the plugin version is the product version', async () => {
  const product = JSON.parse(await read('web/package.json')).version;
  const plugin = JSON.parse(await read('.claude-plugin/plugin.json'));
  assert.equal(plugin.version, product);
  const marketplace = JSON.parse(await read('.claude-plugin/marketplace.json'));
  assert.equal(marketplace.plugins[0].version, undefined, 'plugin.json alone carries the version');
  for (const skill of SKILLS) {
    const { fields } = frontmatter(await read(`skills/${skill.name}/SKILL.md`));
    assert.equal(fields.metadata.version, product, skill.name);
  }
});

test('the marketplace lists the repository root as its one plugin', async () => {
  const marketplace = JSON.parse(await read('.claude-plugin/marketplace.json'));
  const plugin = JSON.parse(await read('.claude-plugin/plugin.json'));
  assert.equal(marketplace.name, 'bounty-operator');
  assert.equal(marketplace.owner.name, 'Tradi3');
  assert.deepEqual(marketplace.plugins.map((entry) => [entry.name, entry.source]), [['bounty-operator', './']]);
  assert.equal(plugin.name, 'bounty-operator');
  assert.equal(plugin.author.name, 'Tradi3');
  assert.equal(plugin.license, 'MIT');
  assert.equal(plugin.repository, 'https://github.com/bountyoperator/bounty-operator');
});

test('the MCP declaration reaches the remote endpoint with empty defaults', async () => {
  const plugin = JSON.parse(await read('.claude-plugin/plugin.json'));
  const server = plugin.mcpServers['bounty-operator'];
  assert.equal(server.type, 'http');
  assert.equal(server.url, 'https://bountyoperator.com/api/mcp');
  assert.deepEqual(server.headers, {
    Authorization: `Bearer \${${TOKEN_VAR}:-}`,
    'X-Provider-Key': `\${${PROVIDER_KEY_VAR}:-}`,
  });
  // The header the endpoint reads, and the token variable the local server reads.
  assert.match(await read('web/src/mcp.ts'), /request\.headers\.get\('x-provider-key'\)/);
  assert.match(await read('mcp/src/hosted.mjs'), new RegExp(`TOKEN_VAR = '${TOKEN_VAR}'`));
});

test('the orchestrators name only tools and codes the servers have', async () => {
  const gauntlet = await read('skills/gauntlet/SKILL.md');
  const tools = (await read('mcp/src/tools.mjs')) + (await read('web/src/mcp.ts'));
  for (const name of ['list_profiles', 'account', 'run_gauntlet_plan', 'run_review', 'prepare_review', 'build_packet']) {
    assert.ok(gauntlet.includes(`\`${name}\``), name);
    assert.ok(tools.includes(`name: '${name}'`), name);
  }
  const failures = gauntlet.slice(gauntlet.indexOf('## When a call fails'));
  const codes = [...failures.matchAll(/^- ((?:`[a-z_]+`(?:, )?)+):/gm)].flatMap((match) => [...match[1].matchAll(/`([a-z_]+)`/g)].map((code) => code[1]));
  const sources = (await read('web/src/review.ts')) + (await read('web/src/auth.ts')) + (await read('mcp/src/tools.mjs')) + (await read('mcp/src/hosted.mjs')) + (await read('web/public/review-core.mjs'));
  assert.ok(codes.length >= 10);
  for (const code of codes) assert.ok(sources.includes(`'${code}'`), `${code} is a code a server raises`);
  assert.equal(GAUNTLET.length, 8);
  assert.deepEqual(GAUNTLET.filter((id) => !PROFILES.find((profile) => profile.id === id).hosted), ['report']);
});

test('the discovery index lists every skill with the digest of its file', async () => {
  const index = JSON.parse(await read('web/public/.well-known/agent-skills/index.json'));
  assert.equal(index.$schema, 'https://schemas.agentskills.io/discovery/0.2.0/schema.json');
  assert.deepEqual(index.skills.map((entry) => entry.name), SKILLS.map((skill) => skill.name));
  const { createHash } = await import('node:crypto');
  for (const entry of index.skills) {
    assert.equal(entry.type, 'skill-md');
    assert.equal(entry.url, `/.well-known/agent-skills/${entry.name}/SKILL.md`);
    const bytes = await readFile(join(ROOT, 'web', 'public', entry.url));
    assert.equal(entry.digest, `sha256:${createHash('sha256').update(bytes).digest('hex')}`);
    assert.equal(bytes.toString('utf8'), await read(`skills/${entry.name}/SKILL.md`));
    assert.ok(entry.description.length <= DESCRIPTION_MAX);
  }
});
